### ISSUE TITLE
Installation routine

### ISSUE THREAD

**Issue by LLTommy** [RDFLib/graph-pattern-learner#2]
Hey,
I stumbled across your project and I think it is interesting, so I wanted to try it but unfortunately it fails during installation. After cloning I initialise the virtual environment and start to install the requirements, but then it fails. It complains about 'error: Error locating graphviz.' and might be related to [this](https://github.com/pygraphviz/pygraphviz/issues/54). I am on a Mac by the way. I don't have the time to really investigate this at the moment though but I thought I let you know so you are aware of this.

**Comment by joernhees** [comment]
yepp, i noticed this recently as well. Seems that on some systems some of the packages behave differently if installed together from a single `pip install -r requirements.txt`. Simply re-running the line several times worked for me ^^

I'll see if i find a more reasonable workaround for this

**Comment by LLTommy** [comment]
Hi unfortunately I can not confirm this. It seems to fail always at the same point at the moment for me at least.  "Failed building wheel for pygraphviz ....   error: Error locating graphviz." I just tried to run it like 10 times, does no help. So.... I am up for a workaround. ;)

**Comment by joernhees** [comment]
could you try looping the following a couple of times?

```
while read line ; do pip install "$line" ; done < requirements.txt
```

**Comment by LLTommy** [comment]
Nope, that did not change anything. It still fails at the same position:
The first error is still 

>   cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c pygraphviz/graphviz_wrap.c -o build/temp.macosx-10.10-intel-2.7/pygraphviz/graphviz_wrap.o
  pygraphviz/graphviz_wrap.c:2954:10: fatal error: 'graphviz/cgraph.h' file not found
  #include "graphviz/cgraph.h"
           ^
  1 error generated.
  error: command 'cc' failed with exit status 1
  Failed building wheel for pygraphviz

It follows with:
>  Your Graphviz installation could not be found. 1) You don't have Graphviz installed:
               Install Graphviz (http://graphviz.org)      2) Your Graphviz package might incomplete.
               Install the binary development subpackage (e.g. libgraphviz-dev or similar.)
So yes, I know there is a problem with graphviz. I could head over there and try to install it manually, however, I feel like the point of pip install is that it does it itself. ;)


Afterwards there are some 'Invalide requirement' statments:
- Invalid requirement: ''
- Invalid requirement: '# cachetools==1.1.6'
- Invalid requirement: '# cycler==0.10.0'
- Invalid requirement: '# deap==1.0.2'
- ....etc 

But these might just be connected to the problem installing graphviz so, I don't care about those too much at this point. 

Cheers!

**Comment by joernhees** [comment]
oups, sorry, forgot about the commented out files starting with `#` in the file... this should've worked:

```
grep -v '^#' requirements.txt | while read line ; do pip install "$line" ; done 
```

i'll reduce the core dependencies a lot so people don't run into this if they don't want any of the visualizations anyhow...

**Comment by LLTommy** [comment]
No unfortunately that does not change anything, still get the very same error.  Don't know what's wrong there.
